Repository Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24, pull requests merged in 2024-09, with the labels that each got.

#26 Db setup
  server/.env
  server/db/connection.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
Labels: Backend

#30 Task.04 - Merge mongoose schemas and updated connection.js
  package-lock.json
  package.json
  server/db/connection.js
  server/db/schemas/course.js
  server/db/schemas/section.js
  server/db/schemas/user.js
  server/routes/api.js
  server/routes/studentLogin.js
Labels: Backend, Features

#33 Add solution to project description
  README.md
Labels: documentation
