Repository Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24, pull requests merged in 2024-11, with the labels that each got.

#72 Sprint2 cleanup
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/AuthProvider.jsx
  client/src/components/Input.jsx
  client/src/components/Navbar.jsx
  client/src/components/StudentView.jsx
  client/src/components/student/StudentAddCourse.jsx
  client/src/components/student/StudentCourseDetails.jsx
  client/src/components/student/StudentLogin.jsx
  client/src/components/student/StudentRegistration.jsx
  client/src/components/student/StudentView.jsx
  client/src/components/teacher/TeacherAddCourse.jsx
  client/src/components/teacher/TeacherCourseDetail.jsx
  client/src/components/teacher/TeacherLogin.jsx
  client/src/components/teacher/TeacherRegistration.jsx
  client/src/components/teacher/TeacherView.jsx
  client/src/main.jsx
  client/src/pages/AddCourse.jsx
  client/src/pages/Registration.jsx
  client/src/pages/StudentRegistration.jsx
  client/src/pages/TeacherCourseDetail.jsx
  client/src/pages/TeacherLogin.jsx
  client/src/pages/UserView.jsx
  client/src/pages/Welcome.jsx
  client/src/pages/old/reg.css
  client/src/pages/old/styles.css
  client/src/pages/old/teacher.css
  client/tailwind.config.js
  server/db/connection.js
  server/package-lock.json
  server/routes/api.js
  server/routes/coursesRouter.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
Labels: bug, enhancement

#54 Added Course creation feature
  client/src/pages/old/reg.css
  server/routes/teacherRouter.js
  server/routes/validation.js
Labels: Frontend, Features

#55 Task.12 Create an express route to access a student's courses
  client/src/App.jsx
  client/src/main.jsx
  client/src/pages/CoursePage.jsx
  client/src/pages/MyCourses.jsx
  client/src/pages/course/CoursePage.css
  client/src/pages/course/StudentCourseView.jsx
  server/db/schemas/course.js
  server/routes/CoursePage.js
  server/routes/studentRouter.js
Labels: Frontend, Backend

#46 Task.11 - Create a page for courses that a student is enrolled in
  client/src/App.jsx
  client/src/main.jsx
  client/src/pages/About.jsx
  server/routes/studentRouter.js
Labels: Frontend, Features

#57 Added Cicd pipeline to host website
  .github/workflows/ci.yml
  client/package-lock.json
  client/src/utils.js
  client/vite.config.js
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/server.js
Labels: Features

#78 Adding Github Actions
  .github/workflows/ci.yml
  client/package-lock.json
  package-lock.json
  server/package-lock.json
Labels: duplicate, enhancement

#81 Added Ratings form
  client/package.json
  client/src/components/student/RatingModal.jsx
  client/src/components/student/StudentView.jsx
  client/src/index.css
  package-lock.json
  package.json
  server/db/connection.js
  server/db/schemas/review.js
  server/routes/coursesRouter.js
Labels: Frontend, Backend, Features

#74 Task.23 Group team members view
  client/src/components/Navbar.jsx
  client/src/components/student/StudentView.jsx
  server/db/connection.js
  server/routes/studentRouter.js
Labels: Frontend, Backend

#76 Create interface for viewing teams on the teacher side
  client/src/components/student/StudentView.jsx
  client/src/components/teacher/TeacherView.jsx
  server/db/connection.js
  server/routes/teacherRouter.js
Labels: Frontend, Backend, Features

#88 added ability for teacher to add student to group
  client/src/components/teacher/TeacherView.jsx
  server/db/connection.js
  server/routes/coursesRouter.js
  server/routes/teacherRouter.js
Labels: Frontend, Backend, Features

#36 Meeting minutes
  client/.vite/deps_temp_b147a0a9/package.json
  meeting-minutes/MegaChugLords_Sprint1_Meeting1_15_09_24.md
  meeting-minutes/MegaChugLords_Sprint1_Meeting2_19_09_24.md
  meeting-minutes/MegaChugLords_Sprint1_Meeting3_26_09_24.md
  meeting-minutes/MegaChugLords_Sprint2_Meeting1_3_10_24.md
  meeting-minutes/MegaChugLords_Sprint2_Meeting2_14_10_24.md
  meeting-minutes/MegaChugLords_Sprint2_Meeting3_24_10_24.md
  meeting-minutes/MegaChugLords_Sprint2_Meeting4_27_10_24.md
  meeting-minutes/MegaChugLords_Sprint3_Meeting1_05_11_24.md
  meeting-minutes/MegaChugLords_Sprint3_Meeting2_07_11_24.md
  meeting-minutes/MegaChugLords_Sprint3_Meeting3_11_11_24.md
  meeting-minutes/MegaChugLords_Sprint3_Meeting4_13_11_24.md
  meeting-minutes/MegaChugLords_Sprint3_Meeting5_14_11_24.md
Labels: documentation

#82 Teacher-dashboard
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/AuthProvider.jsx
  client/src/components/Navbar.jsx
  client/src/components/student/MyTeam.jsx
  client/src/components/student/RatingModal.jsx
  client/src/components/student/StudentAddCourse.jsx
  client/src/components/student/StudentDashboard.jsx
  client/src/components/student/StudentLogin.jsx
  client/src/components/student/StudentView.jsx
  client/src/components/teacher/DetailedCourse.jsx
  client/src/components/teacher/DetailedCourseRow.jsx
  client/src/components/teacher/DetailedDashboard.jsx
  client/src/components/teacher/StudentComment.jsx
  client/src/components/teacher/SummaryCourse.jsx
  client/src/components/teacher/SummaryCourseRow.jsx
  client/src/components/teacher/SummaryDashboard.jsx
  client/src/components/teacher/TeacherLogin.jsx
  client/src/components/teacher/TeacherView.jsx
  client/src/main.jsx
  client/src/pages/Login.jsx
  client/src/pages/TeacherDashboard.jsx
  client/src/pages/old/reg.css
  client/src/pages/old/styles.css
  client/src/pages/old/teacher.css
  package-lock.json
  server/__tests__/acceptanceTestUS03.test.js
  server/__tests__/dashboardFuncs.test.js
  server/db/connection.js
  server/db/schemas/assignment.js
  server/db/schemas/group.js
  server/db/schemas/review.js
  server/package-lock.json
  server/routes/coursesRouter.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
Labels: Features

#93 Added Static Analysis
  README.md
  client/package-lock.json
  client/src/components/student/StudentLogin.jsx
  package-lock.json
  package.json
  server/db/connection.js
  server/db/schemas/group.js
  server/eslint.config.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/coursesRouter.js
  server/routes/validation.js
Labels: enhancement

#95 Sprint3 cleanup
  client/src/components/student/StudentDashboard.jsx
  client/src/components/student/StudentTeam.jsx
  client/src/components/student/StudentView.jsx
  client/src/components/teacher/AddStudentToGroupForm.jsx
  client/src/components/teacher/GroupsDisplay.jsx
  client/src/components/teacher/TeacherLogin.jsx
  client/src/components/teacher/TeacherView.jsx
  server/__tests__/userInfoValidation.test.js
  server/db/connection.js
  server/routes/coursesRouter.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
  server/server.js
Labels: bug

#96 Deployment
  client/src/utils.js
  server/server.js
Labels: enhancement

#97 added linter to ci
  .github/workflows/ci.yml
Labels: enhancement

#100 Add leaderboard for student reviews
  client/package-lock.json
  client/src/App.jsx
  client/src/components/student/StudentDashboard.jsx
  client/src/components/student/StudentView.jsx
  client/src/main.jsx
  client/src/pages/StudentDashboard.jsx
  client/src/utils.js
  server/db/connection.js
  server/package-lock.json
  server/routes/coursesRouter.js
  server/server.js
Labels: enhancement

#79 Student team view and rate feature : Interface for the team view (teammates and rate buttons)
  client/src/components/student/StudentView.jsx
  client/src/main.jsx
  package-lock.json
Labels: enhancement, Frontend, Features

#102 Update README.md
  README.md
Labels: documentation

#105 Fix bug modal for teacher add course wasn't opening/closing
  client/src/components/teacher/TeacherView.jsx
Labels: bug

#107 Add unit tests for fetching groups from db for teacher view
  server/__tests__/fetchCoursesGroups.test.js
Labels: Backend, Features
