Repository Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24, pull requests merged in 2024-10, with the labels that each got.

#34 Task.09 - Create express route for teacher login
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/teacherLogin.js
  server/routes/teacherRegistration.js
Labels: Backend, Features

#35 Merge Task 02 into Task 05
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Input.jsx
  client/src/components/Navbar.jsx
  client/src/components/TeacherRegistration.jsx
  client/src/components/studentregistration.jsx
  client/src/components/validation.js
  client/src/main.jsx
  client/src/pages/About.jsx
  client/src/pages/StudentLogin.jsx
  client/src/pages/StudentRegistration.jsx
  client/src/pages/TeacherLogin.jsx
  client/src/pages/TeacherRegistration.jsx
  client/src/pages/Welcome.jsx
  client/src/pages/reg.css
  server/db/connection.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/old/studentLogin.js
  server/routes/old/teacherLogin.js
  server/routes/old/teacherRegistration.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
  server/routes/validation.js
  server/server.js
Labels: enhancement

#23 Task.05 Create express route for student registration
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Input.jsx
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/About.jsx
  client/src/pages/StudentLogin.jsx
  client/src/pages/StudentRegistration.jsx
  client/src/pages/TeacherLogin.jsx
  client/src/pages/TeacherRegistration.jsx
  client/src/pages/Welcome.jsx
  client/src/pages/reg.css
  client/vite.config.js
  get-pip.py
  package-lock.json
  package.json
  server/db/connection.js
  server/routes/api.js
  server/routes/old/studentLogin.js
  server/routes/old/teacherLogin.js
  server/routes/old/teacherRegistration.js
  server/routes/studentRouter.js
  server/routes/teacherRegistration.js
  server/routes/teacherRouter.js
  server/routes/validation.js
  server/server.js
Labels: Backend, Features

#49 Sprint1 cleanup
  client/package-lock.json
  client/src/pages/StudentLogin.jsx
  client/src/pages/StudentRegistration.jsx
  client/src/pages/TeacherLogin.jsx
  client/src/pages/TeacherRegistration.jsx
  server/db/connection.js
  server/db/schemas/course.js
  server/db/schemas/section.js
  server/db/schemas/user.js
  server/package-lock.json
Labels: bug

#53 Add Review schemas & connection functions
  server/db/connection.js
  server/db/schemas/assignment.js
  server/db/schemas/course.js
  server/db/schemas/group.js
  server/db/schemas/review.js
  server/routes/api.js
Labels: enhancement, Backend

#58 Task.19- Added a route for course creation
  server/routes/api.js
  server/routes/teacherRouter.js
  server/routes/validation.js
Labels: Backend, Features

#62 Persistant User Authentication
  client/package-lock.json
  client/src/App.jsx
  client/src/components/AuthProvider.jsx
  client/src/main.jsx
  client/src/pages/HowToUse.jsx
  client/src/pages/Login.jsx
  client/src/pages/StudentLogin.jsx
  client/src/pages/TeacherLogin.jsx
  client/src/pages/UserView.jsx
  client/src/utils.js
  package-lock.json
  server/__tests__/utils.test.js
  server/db/connection.js
  server/package-lock.json
  server/routes/api.js
  server/routes/old/studentLogin.js
  server/routes/old/teacherLogin.js
  server/routes/old/teacherRegistration.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
  server/server.js
  server/utils.js
Labels: enhancement, Frontend, Backend, Features

#59 Added Course View Component for Teacher
  client/package-lock.json
  client/src/pages/StudentRegistration.jsx
  client/src/pages/TeacherCourseDetail.jsx
  client/src/pages/TeacherRegistration.jsx
  server/db/connection.js
  server/package-lock.json
  server/routes/api.js
  server/routes/studentRouter.js
  server/routes/teacherRouter.js
Labels: Frontend, Backend, Features

#56 Update README.md
  README.md
Labels: documentation

#52 Update README.md
  README.md
Labels: documentation

#61 Added Page for Teacher to View all owned courses
  client/src/App.jsx
  client/src/assets/aboutGIF.gif
  client/src/main.jsx
  client/src/pages/About.jsx
  client/src/pages/TeacherView.jsx
  client/src/pages/teacher.css
  package-lock.json
  package.json
  server/routes/teacherRouter.js
Labels: Frontend, Backend, Features

#71 Create Acceptance Test for Teacher Login
  server/__tests__/acceptanceTestUS02.test.js
Labels: Backend, User Stories

#63 Add Student enrollment to course
  client/package-lock.json
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/components/StudentView.jsx
  client/src/main.jsx
  client/src/pages/About.jsx
  client/src/pages/AddCourse.jsx
  client/src/pages/TeacherCourseDetail.jsx
  client/src/pages/Welcome.jsx
  server/db/connection.js
  server/package-lock.json
  server/routes/api.js
  server/routes/studentRouter.js
Labels: Frontend, Backend, Features
